#!/bin/bash 

timedatectl set-ntp true

parted /dev/sda mklabel gpt -s
parted /dev/sda mkpart ESP fat32 1MiB 513Mib
parted /dev/sda set 1 boot on 
parted /dev/sda mkpart primary linux-swap 4.5GiB 8.5GiB
parted /dev/sda mkpart primary ext4 8.5GiB 100%

mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

mount /dev/sda3 /mnt
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot

pacstrap /mnt base base-devel
genfstab -U /mnt > /mnt/etc/fstab

arch-chroot /mnt /bin/bash

locale > /etc/locale.conf 
echo LANG=en_US.UTF-8 > /etc/locale.conf

ln -sf /usr/share/zoneinfo/US/Central /etc/localtime
hwclock --systohc --utc

mkinitcpio -p linux

pacman -S grub os-prober dosfstools efibootmgr
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck
grub-mkconfig -o /boot/grub/grub.cfg

echo alamo > /etc/hostname
sed -i 's/localhost$/alamo/g' /etc/hosts
