#!/bin/bash 

r() {
  # borrowed from aui
  arch-chroot /mnt /bin/bash -c "${1}"
}

timedatectl set-ntp true

parted /dev/sda mklabel gpt -s
parted /dev/sda mkpart ESP fat32 1MiB 513Mib
parted /dev/sda set 1 boot on 
parted /dev/sda mkpart primary linux-swap 4.5GiB 8.5GiB
parted /dev/sda mkpart primary ext4 8.5GiB 100%

mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

mount /dev/sda3 /mnt
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot

pacstrap /mnt base base-devel

genfstab -U /mnt > /mnt/etc/fstab

r "sed -i 's/#en_US.UTF-8/en_US.UTF-8/' /etc/locale.gen"
r "locale-gen"
r "echo LANG=en_US.UTF-8 >> /etc/locale.conf"

r "ln -sf /usr/share/zoneinfo/US/Central /etc/localtime"
r "hwclock --systohc --utc"

r "mkinitcpio -p linux"

r "bootctl install" 
r "echo title	Arch Linux >> /boot/loader/entries/arch.conf"
r "echo linux	/vmlinuz-linux >> /boot/loader/entries/arch.conf"
r "echo initrd	/initramfs-linux.img >> /boot/loader/entries/arch.conf"
r "echo options	root=/dev/sda3 rw >> /boot/loader/entries/arch.conf"
r "sed -i 's/default.*/default arch/' /boot/loader/loader.conf"

r "echo alamo >> /etc/hostname" 
r "sed -i 's/localhost$/alamo/g' /etc/hosts"
r "systemctl enable dhcpcd@eno1.service"

r "passwd" 

umount -R /mnt
reboot
