#!/bin/bash 

# pacaur 
mkdir ~/builds 

aur() {
  cd ~/builds
  curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz
  tar -xvf $1.tar.gz
  cd $1
  makepkg -sri
}

aur cower 
aur pacaur 

cd ~ 

# x
pacaur -S xorg-xinit xorg-server
echo '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx' >> ~/.bash_profile

# bspwm
pacaur -S bspwm sxhkd xfce4-terminal
echo 'export XDG_CONFIG_HOME="$HOME/.config"' >> ~/.bash_profile
touch ~/.xinitrc
echo -e 'sxhkd &\nexec bspwm' >> ~/.xinitrc
mkdir ~/.config ~/.config/bspwm ~/.config/sxhkd
cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/ 
cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
sed -i 's/urxvt/xfce4-terminal/' ~/.config/sxhkd/sxhkdrc
chmod +x ~/.config/bspwm/bspwmrc
