#!/bin/bash 

mkdir ~/builds 
cd ~/builds

aur() {
  curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz
  tar -xvf $1.tar.gz
  cd $1
  makepkg -sri --skippgpcheck
  cd ..
}

aur cower 
aur pacaur 

pacaur -S nvidia-beta xorg-xinit
