#!/bin/bash 

# pacaur 
mkdir ~/builds 

aur() {
  curl -L -O https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz
  tar -xvf $1.tar.gz
  cd ~/builds/$1
  makepkg -sri --skippgpcheck
  cd ~ 
}

aur cower 
aur pacaur 

# nvidia drivers and x
pacaur -S nvidia-beta xorg-xinit
echo '[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx' >> ~/.bash_profile

# bspwm
pacaur -S bspwm sxhkd
touch ~/.xinitrc
echo -e 'sxhkd &\nexec bspwm' >> ~/.xinitrc
mkdir ~/.config
echo 'XDG_CONFIG_HOME="$HOME/.config"' >> ~/.bash_profile
cp /usr/share/doc/bspwm/examples/bspwmrc ~/.config/bspwm/ 
cp /usr/share/doc/bspwm/examples/sxhkdrc ~/.config/sxhkd/
chmod +x ~/.config/bspwm/bspwmrc
